---
- name: Restart Elasticsearch
  command: "docker restart {{ item }}"
  with_items:
    - "{{ elasticsearch_name }}"

- name: Remove Elasticsearch
  command: "docker stop {{ item }} && docker rm {{ item }}"
  register: results
  with_items:
    - "{{ elasticsearch_name }}"
  failed_when: >-
    results is failed and
    "No such container" not in results.stderr | default(false)
